FROM docker.io/library/node:18.10.0-slim
RUN npm install -g json-server \
    && apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y curl \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ADD run.sh default.json /
ENTRYPOINT ["bash", "/run.sh"]
CMD []
