name: build
on:
  push:
    branches: ['main']

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./pause/Dockerfile
            image: easzlab/pause
            tag: 3.9
            ctx: ./pause/
#          - dockerfile: ./metrics-server/Dockerfile
#            image: easzlab/metrics-server
#            tag: v0.5.2
#            ctx: ./metrics-server/
#          - dockerfile: ./k8s-dns-node-cache/Dockerfile
#            image: easzlab/k8s-dns-node-cache
#            tag: 1.22.8
#            ctx: ./k8s-dns-node-cache/
#          - dockerfile: ./kube-state-metrics/Dockerfile
#            image: easzlab/kube-state-metrics
#            tag: v2.5.0
#            ctx: ./kube-state-metrics/
#          - dockerfile: ./kube-webhook-certgen/Dockerfile
#            image: easzlab/kube-webhook-certgen
#            tag: v1.2.0
#            ctx: ./kube-webhook-certgen/
#          - dockerfile: ./nfs-subdir-external-provisioner/Dockerfile
#            image: easzlab/nfs-subdir-external-provisioner 
#            tag: v4.0.2
#            ctx: ./nfs-subdir-external-provisioner/
#          - dockerfile: ./json-mock/Dockerfile
#            ctx: ./json-mock/
#            image: easzlab/json-mock
#            tag: v1.3.0
#          - dockerfile: ./alpine-curl/Dockerfile
#            ctx: ./alpine-curl/
#            image: easzlab/alpine-curl
#            tag: v7.85.0
#          - dockerfile: ./kube-apiserver/Dockerfile
#            ctx: ./kube-apiserver/
#            image: easzlab/kube-apiserver
#            tag: v1.26.0
#          - dockerfile: ./kube-controller-manager/Dockerfile
#            ctx: ./kube-controller-manager/
#            image: easzlab/kube-controller-manager
#            tag: v1.26.0
#          - dockerfile: ./kube-scheduler/Dockerfile
#            ctx: ./kube-scheduler/
#            image: easzlab/kube-scheduler
#            tag: v1.26.0
#          - dockerfile: ./kube-proxy/Dockerfile
#            ctx: ./kube-proxy/
#            image: easzlab/kube-proxy
#            tag: v1.26.0
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }} 
          tags: ${{ matrix.tag }} 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.ctx }}
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
